 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/instruments", type: :request do
  
  # Instrument. As you add validations to Instrument, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Instrument.create! valid_attributes
      get instruments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      instrument = Instrument.create! valid_attributes
      get instrument_url(instrument)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_instrument_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      instrument = Instrument.create! valid_attributes
      get edit_instrument_url(instrument)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Instrument" do
        expect {
          post instruments_url, params: { instrument: valid_attributes }
        }.to change(Instrument, :count).by(1)
      end

      it "redirects to the created instrument" do
        post instruments_url, params: { instrument: valid_attributes }
        expect(response).to redirect_to(instrument_url(Instrument.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Instrument" do
        expect {
          post instruments_url, params: { instrument: invalid_attributes }
        }.to change(Instrument, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post instruments_url, params: { instrument: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested instrument" do
        instrument = Instrument.create! valid_attributes
        patch instrument_url(instrument), params: { instrument: new_attributes }
        instrument.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the instrument" do
        instrument = Instrument.create! valid_attributes
        patch instrument_url(instrument), params: { instrument: new_attributes }
        instrument.reload
        expect(response).to redirect_to(instrument_url(instrument))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        instrument = Instrument.create! valid_attributes
        patch instrument_url(instrument), params: { instrument: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested instrument" do
      instrument = Instrument.create! valid_attributes
      expect {
        delete instrument_url(instrument)
      }.to change(Instrument, :count).by(-1)
    end

    it "redirects to the instruments list" do
      instrument = Instrument.create! valid_attributes
      delete instrument_url(instrument)
      expect(response).to redirect_to(instruments_url)
    end
  end
end
